### ISSUE TITLE
Using double dollar signs to indicate beginning / end of LaTeX display math mode breaks comment downloading.

### ISSUE THREAD

**Issue by rub-moodle-its** [rwthmoodle/moodle-mod_pdfannotator#40] opened 2020-12-01 17:02 UTC
When using two dollar signs ("$$") to indicate the beginning and end of LaTeX display math mode in a comment, something breaks and prevents comments from being downloaded. Process fails and session is locked for quite a while. Our guess is that pdf compilation fails.

Resulting error message is: "An error has occured while getting all annotations."

Inline math mode with single dollar signs works fine.

Steps to reproduce: Compose a comment with double dollar signs as math mode delimiters, then try to download all comments for the annotated pdf.

**Comment by Friederike-cil** [comment] 2021-04-20 08:01
Hi,
we can't reproduce this with the latest release, so I close this issue now.

**Closed by Friederike-cil** 2021-04-20 08:01 UTC
