### ISSUE TITLE
Strange issue when adding a note with "../../"

### ISSUE THREAD

**Issue by xmarti6** [rwthmoodle/moodle-mod_pdfannotator#48] opened 2021-05-25 11:52 UTC
Hi, 
Congrats for the work on this mod! I recently I came up with an issue when adding notes in our Moodle 2.x. When adding notes related to a programming language I had to add the string "../../", suddenly after introducing this string, the note rises an issue box with "undefined" showing File, Line, and Stack trace fields with "blank" content. I could reproduce this behavior in any note where that string appeared.

I hope this strange issue can be solved. 

Additionally, we would like to mention that  we would find very interesting the ability to select text within the PDF.

Greetings

**Comment by xmarti6** [comment] 2021-05-26 03:59
Same behavior with the string "concat(". We really don't understand what's going on or how to workaround.

**Comment by Friederike-cil** [comment] 2021-05-31 07:07
Hi,
I tested this on our Moodle 3.9 but I can't reproduce this issue.

**Comment by xmarti6** [comment] 2021-06-13 15:35
Hi,
I checked the version in the xml file, which showed "<moodle_release>3.9.1 (Build: 20200713)</moodle_release>"
If we write down this note in the PDF that we are qualifying:

![image](https://user-images.githubusercontent.com/8579969/121813593-f3938e00-cc6c-11eb-9265-9cf2b6071f63.png)

Then, when we click to it to edit the text, or if we create a new note, or we click with the cursor anywhere in the document we get this message all the time:
![image](https://user-images.githubusercontent.com/8579969/121813634-2e95c180-cc6d-11eb-8514-d21f23235b06.png)

It's hard for us to imagine what's going on. Any clue will be apreciated

Thanks

**Comment by Friederike-cil** [comment] 2021-06-14 06:25
ah, thanks for the screenshot.
Your issue is in the assignfeedback_editpdf plugin. But this is the repository of the activity mod_pdfannotator, so I close this issue now.

**Closed by Friederike-cil** 2021-06-14 06:25 UTC
